-- MySQL Script generated by MySQL Workbench
-- Mon Nov 16 17:56:55 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `RUT` VARCHAR(10) NOT NULL,
  `Edad` INT NOT NULL,
  `Telefono` INT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tipo` (
  `idTipo` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Costo_mantencion` INT NOT NULL,
  `Cap_max_transferencia` INT NOT NULL,
  `Cap_min_transferencia` INT NOT NULL,
  PRIMARY KEY (`idTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cuenta` (
  `idCuenta` INT NOT NULL AUTO_INCREMENT,
  `Numero` INT NOT NULL,
  `Saldo` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Tipo_idTipo` INT NOT NULL,
  PRIMARY KEY (`idCuenta`, `Usuario_idUsuario`, `Tipo_idTipo`),
  UNIQUE INDEX `Numero_UNIQUE` (`Numero` ASC) VISIBLE,
  INDEX `fk_Cuenta_Usuario_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Cuenta_Tipo1_idx` (`Tipo_idTipo` ASC) VISIBLE,
  CONSTRAINT `fk_Cuenta_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Cuenta_Tipo1`
    FOREIGN KEY (`Tipo_idTipo`)
    REFERENCES `mydb`.`Tipo` (`idTipo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TransaccionEnviada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TransaccionEnviada` (
  `idTransaccionEnviada` INT NOT NULL AUTO_INCREMENT,
  `Monto` INT NOT NULL,
  `Comentario` VARCHAR(225) NULL,
  `Fecha` TIMESTAMP NOT NULL,
  `Cuenta_idCuenta` INT NOT NULL,
  `Numero_cuenta_destino` INT NOT NULL,
  PRIMARY KEY (`idTransaccionEnviada`, `Cuenta_idCuenta`),
  INDEX `fk_TransaccionEnviada_Cuenta1_idx` (`Cuenta_idCuenta` ASC) VISIBLE,
  CONSTRAINT `fk_TransaccionEnviada_Cuenta1`
    FOREIGN KEY (`Cuenta_idCuenta`)
    REFERENCES `mydb`.`Cuenta` (`idCuenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Servicio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Servicio` (
  `idServicio` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(45) NOT NULL,
  `Saldo` INT NOT NULL,
  PRIMARY KEY (`idServicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pago` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `Monto` INT NOT NULL,
  `Fecha` TIMESTAMP NOT NULL,
  `Cuenta_idCuenta` INT NOT NULL,
  `Servicio_idServicio` INT NOT NULL,
  PRIMARY KEY (`idPago`, `Cuenta_idCuenta`, `Servicio_idServicio`),
  INDEX `fk_Pago_Cuenta1_idx` (`Cuenta_idCuenta` ASC) VISIBLE,
  INDEX `fk_Pago_Servicio1_idx` (`Servicio_idServicio` ASC) VISIBLE,
  CONSTRAINT `fk_Pago_Cuenta1`
    FOREIGN KEY (`Cuenta_idCuenta`)
    REFERENCES `mydb`.`Cuenta` (`idCuenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pago_Servicio1`
    FOREIGN KEY (`Servicio_idServicio`)
    REFERENCES `mydb`.`Servicio` (`idServicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TransaccionRecivida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TransaccionRecivida` (
  `idTransaccionRecivida` INT NOT NULL AUTO_INCREMENT,
  `Cuenta_idCuenta` INT NOT NULL,
  `Monto` INT NOT NULL,
  `Comentario` VARCHAR(45) NULL,
  `Fecha` TIMESTAMP NOT NULL,
  `Numero_cuenta_origen` INT NOT NULL,
  PRIMARY KEY (`idTransaccionRecivida`, `Cuenta_idCuenta`),
  INDEX `fk_TransaccionRecivida_Cuenta1_idx` (`Cuenta_idCuenta` ASC) VISIBLE,
  CONSTRAINT `fk_TransaccionRecivida_Cuenta1`
    FOREIGN KEY (`Cuenta_idCuenta`)
    REFERENCES `mydb`.`Cuenta` (`idCuenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
